# Generated by Django 5.0.3 on 2024-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_assinante', models.CharField(default=None, max_length=50)),
                ('valor_assinatura', models.FloatField()),
            ],
        ),
    ]
