# Generated by Django 5.0.3 on 2024-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_itemcarrinho_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
