# Generated by Django 5.0.3 on 2024-05-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(default=False, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='produtos.categoriaproduto'),
        ),
    ]
