# Generated by Django 5.0.3 on 2024-05-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
