# Generated by Django 5.0.3 on 2024-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_product_remove_produto_tipo_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
