# Generated by Django 5.0.3 on 2024-04-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotoken',
            name='nome_aleatorio',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
