# Generated by Django 5.0.3 on 2024-04-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0003_registrotoken_nome_aleatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotoken',
            name='nome_aleatorio',
        ),
    ]
