# Generated by Django 5.0.3 on 2024-04-26 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0004_remove_registrotoken_nome_aleatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotoken',
            name='token_criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
